[package]
name = "remi_browser"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.31.0", features = ["persistence"] }
rustls = { version = "0.23.23", features = ["std", "tls12", "ring"], default-features = false }
